name: Count Commits

on:
  push:
    branches:
      - main

jobs:
  count-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Count Commits
        id: count
        run: echo "::set-output name=commit_count::$(git rev-list --count HEAD)"
      - name: Display Count
        run: echo "Number of commits:${{ steps.count.outputs.commit_count }}"